### ISSUE TITLE
JUJIMEIZUO!!!

### ISSUE THREAD

**Issue by rethus** [jujimeizuo/jujimeizuo#1]
Hello, Mr.Tiao. Can you teach me some skills about building blog on GitHub?

**Comment by jujimeizuo** [comment]
Sorry，I don't build github.io on Github，cause I use wordpress to build my [blog](http://www.jujimeizuo.cn/blog).

You can ask [Mr.Wang](https://github.com/ricar0) some questions when it comes to github.io. Maybe it will help you a little bit.
